# Generated by Django 2.2.20 on 2021-04-29 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasforfront', '0003_auto_20210430_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorofbook',
            options={'verbose_name': 'Author Of Book', 'verbose_name_plural': 'Authors Of Books'},
        ),
        migrations.AddField(
            model_name='authorofbook',
            name='book_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='products',
            name='author_book',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='datasforfront.AuthorOfBook'),
        ),
        migrations.AlterField(
            model_name='authorofbook',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
