# Generated by Django 2.2.20 on 2021-04-29 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasforfront', '0004_auto_20210430_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorofbook',
            old_name='name',
            new_name='name_of_author',
        ),
    ]
